# Generated by Django 2.2.16 on 2022-07-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=120)),
                ('answer', models.CharField(max_length=120)),
                ('wrong_answer_1', models.CharField(max_length=120)),
                ('wrong_answer_2', models.CharField(max_length=120)),
                ('wrong_answer_3', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('min_right', models.IntegerField()),
                ('difficult', models.CharField(choices=[('HARD', 'Hard'), ('NORMAL', 'Normal'), ('SIMPLE', 'Simple')], max_length=10)),
                ('questions', models.ManyToManyField(related_name='questions', to='quiz.Question')),
            ],
        ),
    ]
