# Generated by Django 2.2.16 on 2022-07-28 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=120)),
                ('num_of_right_answer', models.IntegerField(verbose_name='Номер правильного ответа:')),
                ('answers', models.ManyToManyField(related_name='answers', through='quiz.AnswerAmount', to='quiz.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('min_right_answers', models.IntegerField(verbose_name='Минимальное количество ответов для прохождение теста')),
                ('difficult', models.IntegerField(choices=[(20, 'Сложный'), (15, 'Нормальный'), (10, 'Простой')], default=0)),
                ('questions', models.ManyToManyField(related_name='questions', to='quiz.Question')),
            ],
        ),
        migrations.CreateModel(
            name='DoneQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donequizs', to='quiz.Quiz')),
            ],
        ),
    ]
