# Generated by Django 2.2.16 on 2022-07-28 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donequiz',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userdonequizs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answeramount',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='quiz.Answer', verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='answeramount',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='quiz.Question', verbose_name='Вопрос'),
        ),
    ]
