# Generated by Django 2.2.16 on 2022-07-27 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_donequiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donequiz',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donequizs', to='quiz.Quiz'),
        ),
        migrations.AlterField(
            model_name='donequiz',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userdonequizs', to=settings.AUTH_USER_MODEL),
        ),
    ]
