# Generated by Django 2.2.16 on 2022-07-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_done_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='color',
            field=models.CharField(default='white', max_length=16),
        ),
    ]
